.TH kube 1

.SH NAME
kube \- an optimal solver for the 3x3x3 Rubik's cube

.SH SYNOPSIS
.B kube
[\fB\-f\fR \fIFORMAT\fR]
[\fB\-g\fR]
[\fB\-i\fR]
[\fB\-M\fR \fIMAX\fR]
[\fB\-n\fR \fINUM\fR]
[\fB\-s\fR \fISTEP\fR]...
[\fB\-t\fR \fINUM\fR]
[\fB\-v\fR]
[\fB\-?\fR]
[\fB\-V\fR]

.SH DESCRIPTION
.B kube
is an optimal solver for the 3x3x3 Rubik's cube.
It finds a shortest solution to the given scramble
in the half turn metric (HTM). The solving
algorithm is heavily inspired by Tomas Rokicki's
nxopt solver.

When multiple solving steps are specified,
.B kube
uses a beam search to find up to
\fINUM\fR solutions.

.PP
.B kube
reads the scramble provided as the [SCRAMBLE] argument.
Multiple scrambles can by provided via stdin if the \fI-i\fR flag is set. They are separated by newlines.
The scrambles format is specified by \fIFORMAT\fR.

.SH OPTIONS

.TP
.BR \-f " " \fIFORMAT\fR ", " \-\-format=FORMAT
Specify scramble format. Default is "singmaster".

Supported formats:

.RS
.TP
.B singmaster
Standard move notation (e.g., "R U R' F B2"). Writing e.g. R1, R2, R3 instead of R, R2, R' is also supported.

.TP
.B speffz
Blindfold memo using the Speffz letter scheme
from buffers UFR/UF. Corner memo first, then a ".",
followed by edge memo (e.g., "abuv.efnt").
.RE

.TP
.BR \-g ", " \-\-gen
Generate pruning tables. This must be done before
using the solver.

.TP
.BR \-i ", " \-\-stdin
Read scrambles from stdin instead. Separate scrambles with newlines.

.TP
.BR \-M " " \fIMAX\fR ", " \-\-max-depth=MAX
Limit the search depth to \fIMAX\fR moves. Default is 1024.

.TP
.BR \-n " " \fINUM\fR ", " \-\-num=NUM
Try to find \fINUM\fR solutions. Default is 1.
When multiple solving steps are provided,
kube performs a beam search to find up to \fINUM\fR
solutions.

.TP
.BR \-s " " \fISTEP\fR ", " \-\-step=STEP
Append a solving step. Steps are executed in the
order they are given. This option may be repeated.

Supported steps:
.RS
eo, dr, htr, fin
.RE

Example:
.RS
kube -s eo -s dr -s fin
.RE

.TP
.BR \-t " " \fINUM\fR
Specify number of threads for the optimal solver.
Defaults to the number of cpus on the system.

.TP
.BR \-v ", " \-\-verbose
Produce verbose output. kube prints statistics about
the solving process.

.TP
.BR \-? ", " \-\-help
Gives a help list.

.TP
.BR \-V ", " \-\-version
Print program version


.SH EXAMPLES

.PP
Find an optimal solution for a simple scramble with comment:
.PP
.nf
.RS
.B
kube -s fin "R U F // this is a comment and will be ignored by kube"
.RE
.fi

.PP
Find an optimal solution to dr and then to solved with niss eo:
.PP
.nf
.RS
.B
kube --step dr --step fin "R' U' F L D2 B' U2 R2 B' D2 L2 B D2 L2 B2 R F D' B' D L2 B U R' U' F // scramble
F' U (L U) // eo"
.RE
.fi

.PP
Find an optimal solution for the Ua-perm with verbose output:
.PP
.nf
.RS
.B
echo "R' U R' U' R' U' R' U R U R2" | kube -s fin -v
.RE
.fi

.PP
Find an optimal solution for an A-perm using Speffz format:
.PP
.nf
.RS
.B
echo "ab." | kube -s fin -f speffz
.RE
.fi

.SH AUTHORS
Oskar Feed Jakobsen (oskarfj@oskarfj.no)

.SH SOURCE CODE
Source code is available at:
.I https://github.com/kajrakso/kube

